// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// getProbRR_org_cpp
Rcpp::List getProbRR_org_cpp(const Rcpp::NumericVector& logrr, const Rcpp::NumericVector& logop, double clipping);
RcppExport SEXP _rbrm_getProbRR_org_cpp(SEXP logrrSEXP, SEXP logopSEXP, SEXP clippingSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type logrr(logrrSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type logop(logopSEXP);
    Rcpp::traits::input_parameter< double >::type clipping(clippingSEXP);
    rcpp_result_gen = Rcpp::wrap(getProbRR_org_cpp(logrr, logop, clipping));
    return rcpp_result_gen;
END_RCPP
}
// getProbRR_alt_cpp
Rcpp::List getProbRR_alt_cpp(const Rcpp::NumericVector& logrr, const Rcpp::NumericVector& logop, double clipping);
RcppExport SEXP _rbrm_getProbRR_alt_cpp(SEXP logrrSEXP, SEXP logopSEXP, SEXP clippingSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type logrr(logrrSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type logop(logopSEXP);
    Rcpp::traits::input_parameter< double >::type clipping(clippingSEXP);
    rcpp_result_gen = Rcpp::wrap(getProbRR_alt_cpp(logrr, logop, clipping));
    return rcpp_result_gen;
END_RCPP
}
// soft_thres_cpp
Rcpp::NumericVector soft_thres_cpp(Rcpp::NumericVector x, double lambda);
RcppExport SEXP _rbrm_soft_thres_cpp(SEXP xSEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(soft_thres_cpp(x, lambda));
    return rcpp_result_gen;
END_RCPP
}
// nllh_cpp
double nllh_cpp(const arma::vec& alpha, const arma::vec& beta, const arma::mat& va, const arma::mat& vb, const Rcpp::NumericVector& x_indicator, const Rcpp::NumericVector& y_outcome, int prob_fun, double clipping);
RcppExport SEXP _rbrm_nllh_cpp(SEXP alphaSEXP, SEXP betaSEXP, SEXP vaSEXP, SEXP vbSEXP, SEXP x_indicatorSEXP, SEXP y_outcomeSEXP, SEXP prob_funSEXP, SEXP clippingSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type va(vaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type vb(vbSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type x_indicator(x_indicatorSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type y_outcome(y_outcomeSEXP);
    Rcpp::traits::input_parameter< int >::type prob_fun(prob_funSEXP);
    Rcpp::traits::input_parameter< double >::type clipping(clippingSEXP);
    rcpp_result_gen = Rcpp::wrap(nllh_cpp(alpha, beta, va, vb, x_indicator, y_outcome, prob_fun, clipping));
    return rcpp_result_gen;
END_RCPP
}
// penalized_nllh_cpp
double penalized_nllh_cpp(const arma::vec& alpha, const arma::vec& beta, const arma::mat& va, const arma::mat& vb, const Rcpp::NumericVector& x_indicator, const Rcpp::NumericVector& y_outcome, double lambda, bool intercept, int prob_fun, double clipping);
RcppExport SEXP _rbrm_penalized_nllh_cpp(SEXP alphaSEXP, SEXP betaSEXP, SEXP vaSEXP, SEXP vbSEXP, SEXP x_indicatorSEXP, SEXP y_outcomeSEXP, SEXP lambdaSEXP, SEXP interceptSEXP, SEXP prob_funSEXP, SEXP clippingSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type va(vaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type vb(vbSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type x_indicator(x_indicatorSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type y_outcome(y_outcomeSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< bool >::type intercept(interceptSEXP);
    Rcpp::traits::input_parameter< int >::type prob_fun(prob_funSEXP);
    Rcpp::traits::input_parameter< double >::type clipping(clippingSEXP);
    rcpp_result_gen = Rcpp::wrap(penalized_nllh_cpp(alpha, beta, va, vb, x_indicator, y_outcome, lambda, intercept, prob_fun, clipping));
    return rcpp_result_gen;
END_RCPP
}
// grad_nll_alpha_analytical_cpp
arma::vec grad_nll_alpha_analytical_cpp(const arma::vec& alpha, const arma::vec& beta, const arma::mat& va, const arma::mat& vb, const Rcpp::NumericVector& x_indicator, const Rcpp::NumericVector& y_outcome, int prob_fun_selector, double clipping);
RcppExport SEXP _rbrm_grad_nll_alpha_analytical_cpp(SEXP alphaSEXP, SEXP betaSEXP, SEXP vaSEXP, SEXP vbSEXP, SEXP x_indicatorSEXP, SEXP y_outcomeSEXP, SEXP prob_fun_selectorSEXP, SEXP clippingSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type va(vaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type vb(vbSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type x_indicator(x_indicatorSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type y_outcome(y_outcomeSEXP);
    Rcpp::traits::input_parameter< int >::type prob_fun_selector(prob_fun_selectorSEXP);
    Rcpp::traits::input_parameter< double >::type clipping(clippingSEXP);
    rcpp_result_gen = Rcpp::wrap(grad_nll_alpha_analytical_cpp(alpha, beta, va, vb, x_indicator, y_outcome, prob_fun_selector, clipping));
    return rcpp_result_gen;
END_RCPP
}
// grad_nll_beta_analytical_cpp
arma::vec grad_nll_beta_analytical_cpp(const arma::vec& alpha, const arma::vec& beta, const arma::mat& va, const arma::mat& vb, const Rcpp::NumericVector& x_indicator, const Rcpp::NumericVector& y_outcome, int prob_fun_selector, double clipping);
RcppExport SEXP _rbrm_grad_nll_beta_analytical_cpp(SEXP alphaSEXP, SEXP betaSEXP, SEXP vaSEXP, SEXP vbSEXP, SEXP x_indicatorSEXP, SEXP y_outcomeSEXP, SEXP prob_fun_selectorSEXP, SEXP clippingSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type va(vaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type vb(vbSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type x_indicator(x_indicatorSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type y_outcome(y_outcomeSEXP);
    Rcpp::traits::input_parameter< int >::type prob_fun_selector(prob_fun_selectorSEXP);
    Rcpp::traits::input_parameter< double >::type clipping(clippingSEXP);
    rcpp_result_gen = Rcpp::wrap(grad_nll_beta_analytical_cpp(alpha, beta, va, vb, x_indicator, y_outcome, prob_fun_selector, clipping));
    return rcpp_result_gen;
END_RCPP
}
// newton_cd_cpp
Rcpp::List newton_cd_cpp(Rcpp::NumericVector alpha_start_rcpp, Rcpp::NumericVector beta_start_rcpp, double lambda, bool intercept, int max_iter, Rcpp::NumericMatrix va_rcpp, Rcpp::NumericMatrix vb_rcpp, Rcpp::NumericVector x_indicator, Rcpp::NumericVector y_outcome, int prob_fun_selector, double lambda_beta, double tol, double clipping, bool save_history);
RcppExport SEXP _rbrm_newton_cd_cpp(SEXP alpha_start_rcppSEXP, SEXP beta_start_rcppSEXP, SEXP lambdaSEXP, SEXP interceptSEXP, SEXP max_iterSEXP, SEXP va_rcppSEXP, SEXP vb_rcppSEXP, SEXP x_indicatorSEXP, SEXP y_outcomeSEXP, SEXP prob_fun_selectorSEXP, SEXP lambda_betaSEXP, SEXP tolSEXP, SEXP clippingSEXP, SEXP save_historySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type alpha_start_rcpp(alpha_start_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type beta_start_rcpp(beta_start_rcppSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< bool >::type intercept(interceptSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type va_rcpp(va_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type vb_rcpp(vb_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x_indicator(x_indicatorSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type y_outcome(y_outcomeSEXP);
    Rcpp::traits::input_parameter< int >::type prob_fun_selector(prob_fun_selectorSEXP);
    Rcpp::traits::input_parameter< double >::type lambda_beta(lambda_betaSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< double >::type clipping(clippingSEXP);
    Rcpp::traits::input_parameter< bool >::type save_history(save_historySEXP);
    rcpp_result_gen = Rcpp::wrap(newton_cd_cpp(alpha_start_rcpp, beta_start_rcpp, lambda, intercept, max_iter, va_rcpp, vb_rcpp, x_indicator, y_outcome, prob_fun_selector, lambda_beta, tol, clipping, save_history));
    return rcpp_result_gen;
END_RCPP
}
// active_set_newton_cd_cpp
Rcpp::List active_set_newton_cd_cpp(Rcpp::NumericVector alpha_start_rcpp, Rcpp::NumericVector beta_start_rcpp, double lambda, bool intercept, int max_iter, Rcpp::NumericMatrix va_rcpp, Rcpp::NumericMatrix vb_rcpp, Rcpp::NumericVector x_indicator, Rcpp::NumericVector y_outcome, int prob_fun_selector, double lambda_beta, double tol, double clipping, int kkt_check_freq, double active_tol, bool save_history);
RcppExport SEXP _rbrm_active_set_newton_cd_cpp(SEXP alpha_start_rcppSEXP, SEXP beta_start_rcppSEXP, SEXP lambdaSEXP, SEXP interceptSEXP, SEXP max_iterSEXP, SEXP va_rcppSEXP, SEXP vb_rcppSEXP, SEXP x_indicatorSEXP, SEXP y_outcomeSEXP, SEXP prob_fun_selectorSEXP, SEXP lambda_betaSEXP, SEXP tolSEXP, SEXP clippingSEXP, SEXP kkt_check_freqSEXP, SEXP active_tolSEXP, SEXP save_historySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type alpha_start_rcpp(alpha_start_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type beta_start_rcpp(beta_start_rcppSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< bool >::type intercept(interceptSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type va_rcpp(va_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type vb_rcpp(vb_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x_indicator(x_indicatorSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type y_outcome(y_outcomeSEXP);
    Rcpp::traits::input_parameter< int >::type prob_fun_selector(prob_fun_selectorSEXP);
    Rcpp::traits::input_parameter< double >::type lambda_beta(lambda_betaSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< double >::type clipping(clippingSEXP);
    Rcpp::traits::input_parameter< int >::type kkt_check_freq(kkt_check_freqSEXP);
    Rcpp::traits::input_parameter< double >::type active_tol(active_tolSEXP);
    Rcpp::traits::input_parameter< bool >::type save_history(save_historySEXP);
    rcpp_result_gen = Rcpp::wrap(active_set_newton_cd_cpp(alpha_start_rcpp, beta_start_rcpp, lambda, intercept, max_iter, va_rcpp, vb_rcpp, x_indicator, y_outcome, prob_fun_selector, lambda_beta, tol, clipping, kkt_check_freq, active_tol, save_history));
    return rcpp_result_gen;
END_RCPP
}
// fista_cpp
Rcpp::List fista_cpp(Rcpp::NumericVector alpha_start_rcpp, Rcpp::NumericVector beta_start_rcpp, double lambda, bool intercept, int max_iter, Rcpp::NumericMatrix va_rcpp, Rcpp::NumericMatrix vb_rcpp, Rcpp::NumericVector x_indicator, Rcpp::NumericVector y_outcome, int prob_fun_selector, double lambda_beta, double tol, double step_size_init, double armijo_c, double shrink_factor, double clipping, bool save_history);
RcppExport SEXP _rbrm_fista_cpp(SEXP alpha_start_rcppSEXP, SEXP beta_start_rcppSEXP, SEXP lambdaSEXP, SEXP interceptSEXP, SEXP max_iterSEXP, SEXP va_rcppSEXP, SEXP vb_rcppSEXP, SEXP x_indicatorSEXP, SEXP y_outcomeSEXP, SEXP prob_fun_selectorSEXP, SEXP lambda_betaSEXP, SEXP tolSEXP, SEXP step_size_initSEXP, SEXP armijo_cSEXP, SEXP shrink_factorSEXP, SEXP clippingSEXP, SEXP save_historySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type alpha_start_rcpp(alpha_start_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type beta_start_rcpp(beta_start_rcppSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< bool >::type intercept(interceptSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type va_rcpp(va_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type vb_rcpp(vb_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x_indicator(x_indicatorSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type y_outcome(y_outcomeSEXP);
    Rcpp::traits::input_parameter< int >::type prob_fun_selector(prob_fun_selectorSEXP);
    Rcpp::traits::input_parameter< double >::type lambda_beta(lambda_betaSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< double >::type step_size_init(step_size_initSEXP);
    Rcpp::traits::input_parameter< double >::type armijo_c(armijo_cSEXP);
    Rcpp::traits::input_parameter< double >::type shrink_factor(shrink_factorSEXP);
    Rcpp::traits::input_parameter< double >::type clipping(clippingSEXP);
    Rcpp::traits::input_parameter< bool >::type save_history(save_historySEXP);
    rcpp_result_gen = Rcpp::wrap(fista_cpp(alpha_start_rcpp, beta_start_rcpp, lambda, intercept, max_iter, va_rcpp, vb_rcpp, x_indicator, y_outcome, prob_fun_selector, lambda_beta, tol, step_size_init, armijo_c, shrink_factor, clipping, save_history));
    return rcpp_result_gen;
END_RCPP
}
// lbfgs_cpp
Rcpp::List lbfgs_cpp(Rcpp::NumericVector alpha_start_rcpp, Rcpp::NumericVector beta_start_rcpp, double lambda, bool intercept, int max_iter, Rcpp::NumericMatrix va_rcpp, Rcpp::NumericMatrix vb_rcpp, Rcpp::NumericVector x_indicator, Rcpp::NumericVector y_outcome, int prob_fun_selector, double lambda_beta, double tol, double clipping, bool save_history);
RcppExport SEXP _rbrm_lbfgs_cpp(SEXP alpha_start_rcppSEXP, SEXP beta_start_rcppSEXP, SEXP lambdaSEXP, SEXP interceptSEXP, SEXP max_iterSEXP, SEXP va_rcppSEXP, SEXP vb_rcppSEXP, SEXP x_indicatorSEXP, SEXP y_outcomeSEXP, SEXP prob_fun_selectorSEXP, SEXP lambda_betaSEXP, SEXP tolSEXP, SEXP clippingSEXP, SEXP save_historySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type alpha_start_rcpp(alpha_start_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type beta_start_rcpp(beta_start_rcppSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< bool >::type intercept(interceptSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type va_rcpp(va_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type vb_rcpp(vb_rcppSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x_indicator(x_indicatorSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type y_outcome(y_outcomeSEXP);
    Rcpp::traits::input_parameter< int >::type prob_fun_selector(prob_fun_selectorSEXP);
    Rcpp::traits::input_parameter< double >::type lambda_beta(lambda_betaSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< double >::type clipping(clippingSEXP);
    Rcpp::traits::input_parameter< bool >::type save_history(save_historySEXP);
    rcpp_result_gen = Rcpp::wrap(lbfgs_cpp(alpha_start_rcpp, beta_start_rcpp, lambda, intercept, max_iter, va_rcpp, vb_rcpp, x_indicator, y_outcome, prob_fun_selector, lambda_beta, tol, clipping, save_history));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rbrm_getProbRR_org_cpp", (DL_FUNC) &_rbrm_getProbRR_org_cpp, 3},
    {"_rbrm_getProbRR_alt_cpp", (DL_FUNC) &_rbrm_getProbRR_alt_cpp, 3},
    {"_rbrm_soft_thres_cpp", (DL_FUNC) &_rbrm_soft_thres_cpp, 2},
    {"_rbrm_nllh_cpp", (DL_FUNC) &_rbrm_nllh_cpp, 8},
    {"_rbrm_penalized_nllh_cpp", (DL_FUNC) &_rbrm_penalized_nllh_cpp, 10},
    {"_rbrm_grad_nll_alpha_analytical_cpp", (DL_FUNC) &_rbrm_grad_nll_alpha_analytical_cpp, 8},
    {"_rbrm_grad_nll_beta_analytical_cpp", (DL_FUNC) &_rbrm_grad_nll_beta_analytical_cpp, 8},
    {"_rbrm_newton_cd_cpp", (DL_FUNC) &_rbrm_newton_cd_cpp, 14},
    {"_rbrm_active_set_newton_cd_cpp", (DL_FUNC) &_rbrm_active_set_newton_cd_cpp, 16},
    {"_rbrm_fista_cpp", (DL_FUNC) &_rbrm_fista_cpp, 17},
    {"_rbrm_lbfgs_cpp", (DL_FUNC) &_rbrm_lbfgs_cpp, 14},
    {NULL, NULL, 0}
};

RcppExport void R_init_rbrm(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
