# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getProbRR_org_cpp <- function(logrr, logop, clipping = 1e-15) {
    .Call(`_rbrm_getProbRR_org_cpp`, logrr, logop, clipping)
}

getProbRR_alt_cpp <- function(logrr, logop, clipping = 1e-15) {
    .Call(`_rbrm_getProbRR_alt_cpp`, logrr, logop, clipping)
}

soft_thres_cpp <- function(x, lambda) {
    .Call(`_rbrm_soft_thres_cpp`, x, lambda)
}

nllh_cpp <- function(alpha, beta, va, vb, x_indicator, y_outcome, prob_fun, clipping = 1e-10) {
    .Call(`_rbrm_nllh_cpp`, alpha, beta, va, vb, x_indicator, y_outcome, prob_fun, clipping)
}

penalized_nllh_cpp <- function(alpha, beta, va, vb, x_indicator, y_outcome, lambda, intercept, prob_fun, clipping = 1e-10) {
    .Call(`_rbrm_penalized_nllh_cpp`, alpha, beta, va, vb, x_indicator, y_outcome, lambda, intercept, prob_fun, clipping)
}

grad_nll_alpha_analytical_cpp <- function(alpha, beta, va, vb, x_indicator, y_outcome, prob_fun_selector, clipping = 1e-10) {
    .Call(`_rbrm_grad_nll_alpha_analytical_cpp`, alpha, beta, va, vb, x_indicator, y_outcome, prob_fun_selector, clipping)
}

grad_nll_beta_analytical_cpp <- function(alpha, beta, va, vb, x_indicator, y_outcome, prob_fun_selector, clipping = 1e-10) {
    .Call(`_rbrm_grad_nll_beta_analytical_cpp`, alpha, beta, va, vb, x_indicator, y_outcome, prob_fun_selector, clipping)
}

newton_cd_cpp <- function(alpha_start_rcpp, beta_start_rcpp, lambda, intercept, max_iter, va_rcpp, vb_rcpp, x_indicator, y_outcome, prob_fun_selector, lambda_beta = -1.0, tol = 1e-5, clipping = 1e-10, save_history = FALSE) {
    .Call(`_rbrm_newton_cd_cpp`, alpha_start_rcpp, beta_start_rcpp, lambda, intercept, max_iter, va_rcpp, vb_rcpp, x_indicator, y_outcome, prob_fun_selector, lambda_beta, tol, clipping, save_history)
}

active_set_newton_cd_cpp <- function(alpha_start_rcpp, beta_start_rcpp, lambda, intercept, max_iter, va_rcpp, vb_rcpp, x_indicator, y_outcome, prob_fun_selector, lambda_beta = -1.0, tol = 1e-5, clipping = 1e-10, kkt_check_freq = 10L, active_tol = 1e-6, save_history = FALSE) {
    .Call(`_rbrm_active_set_newton_cd_cpp`, alpha_start_rcpp, beta_start_rcpp, lambda, intercept, max_iter, va_rcpp, vb_rcpp, x_indicator, y_outcome, prob_fun_selector, lambda_beta, tol, clipping, kkt_check_freq, active_tol, save_history)
}

fista_cpp <- function(alpha_start_rcpp, beta_start_rcpp, lambda, intercept, max_iter, va_rcpp, vb_rcpp, x_indicator, y_outcome, prob_fun_selector, lambda_beta = -1.0, tol = 1e-5, step_size_init = 0.5, armijo_c = 1e-4, shrink_factor = 0.5, clipping = 1e-10, save_history = FALSE) {
    .Call(`_rbrm_fista_cpp`, alpha_start_rcpp, beta_start_rcpp, lambda, intercept, max_iter, va_rcpp, vb_rcpp, x_indicator, y_outcome, prob_fun_selector, lambda_beta, tol, step_size_init, armijo_c, shrink_factor, clipping, save_history)
}

lbfgs_cpp <- function(alpha_start_rcpp, beta_start_rcpp, lambda, intercept, max_iter, va_rcpp, vb_rcpp, x_indicator, y_outcome, prob_fun_selector, lambda_beta = -1.0, tol = 1e-5, clipping = 1e-10, save_history = FALSE) {
    .Call(`_rbrm_lbfgs_cpp`, alpha_start_rcpp, beta_start_rcpp, lambda, intercept, max_iter, va_rcpp, vb_rcpp, x_indicator, y_outcome, prob_fun_selector, lambda_beta, tol, clipping, save_history)
}

